id: P29441874
initial_creation_type: input
source_metadata:
  title: Jigdral Tutop Lingpa Series
  language: bo
  description: 'Texts revealed by the tertön Ngawang Tendzin (ngag dbang bstan ''dzin,
    1858–1914) also known as Jigdral Tutop Lingpa (''jigs bral mthu stobs gling pa):'
  volume:
    2a43c3571093483a93b89afcf1f25375:
      title: A Powerful Pith Instruction to Abstain from Tobacco, the Tenacious Demon
        Plaguing People of Degenerate Times
      parent: Ethical Guidelines
created_at: '2022-03-01T00:02:53.328564'
last_modified_at: '2022-03-01T00:02:53.328566'
